package cc.jaxy.anlobehub.core.designsystem.component

import androidx.annotation.DrawableRes
import cc.jaxy.anlobehub.core.designsystem.R

/** Generated by `scripts/sync_provider_icons.py`; do not hand-edit. */
@DrawableRes
fun providerBrandIcon(providerId: String): Int? {
    return when (providerId.lowercase()) {
        "ai21" -> R.drawable.ic_provider_ai21
        "ai302" -> R.drawable.ic_provider_ai302
        "ai360" -> R.drawable.ic_provider_ai360
        "aihubmix" -> R.drawable.ic_provider_aihubmix
        "akashchat" -> R.drawable.ic_provider_akashchat
        "antgroup" -> R.drawable.ic_provider_antgroup
        "anthropic" -> R.drawable.ic_provider_anthropic
        "azure" -> R.drawable.ic_provider_azure
        "azureai" -> R.drawable.ic_provider_azureai
        "baichuan" -> R.drawable.ic_provider_baichuan
        "bailiancodingplan" -> R.drawable.ic_provider_bailiancodingplan
        "bedrock" -> R.drawable.ic_provider_bedrock
        "bfl" -> R.drawable.ic_provider_bfl
        "cerebras" -> R.drawable.ic_provider_cerebras
        "chatgpt" -> R.drawable.ic_provider_chatgpt
        "cloudflare" -> R.drawable.ic_provider_cloudflare
        "cohere" -> R.drawable.ic_provider_cohere
        "cometapi" -> R.drawable.ic_provider_cometapi
        "comfyui" -> R.drawable.ic_provider_comfyui
        "deepseek" -> R.drawable.ic_provider_deepseek
        "fal" -> R.drawable.ic_provider_fal
        "fireworksai" -> R.drawable.ic_provider_fireworksai
        "giteeai" -> R.drawable.ic_provider_giteeai
        "github" -> R.drawable.ic_provider_github
        "githubcopilot" -> R.drawable.ic_provider_githubcopilot
        "glmcodingplan" -> R.drawable.ic_provider_glmcodingplan
        "google" -> R.drawable.ic_provider_google
        "groq" -> R.drawable.ic_provider_groq
        "higress" -> R.drawable.ic_provider_higress
        "huggingface" -> R.drawable.ic_provider_huggingface
        "hunyuan" -> R.drawable.ic_provider_hunyuan
        "infiniai" -> R.drawable.ic_provider_infiniai
        "internlm" -> R.drawable.ic_provider_internlm
        "jina" -> R.drawable.ic_provider_jina
        "kimicodingplan" -> R.drawable.ic_provider_kimicodingplan
        "lmstudio" -> R.drawable.ic_provider_lmstudio
        "lobehub" -> R.drawable.ic_provider_lobehub
        "longcat" -> R.drawable.ic_provider_longcat
        "meta" -> R.drawable.ic_provider_meta
        "minimax" -> R.drawable.ic_provider_minimax
        "minimaxcodingplan" -> R.drawable.ic_provider_minimaxcodingplan
        "mistral" -> R.drawable.ic_provider_mistral
        "modelscope" -> R.drawable.ic_provider_modelscope
        "moonshot" -> R.drawable.ic_provider_moonshot
        "nebius" -> R.drawable.ic_provider_nebius
        "newapi" -> R.drawable.ic_provider_newapi
        "novita" -> R.drawable.ic_provider_novita
        "nvidia" -> R.drawable.ic_provider_nvidia
        "ollama" -> R.drawable.ic_provider_ollama
        "ollamacloud" -> R.drawable.ic_provider_ollamacloud
        "openai" -> R.drawable.ic_provider_openai
        "opencodecodingplan" -> R.drawable.ic_provider_opencodecodingplan
        "opencodezen" -> R.drawable.ic_provider_opencodezen
        "openrouter" -> R.drawable.ic_provider_openrouter
        "perplexity" -> R.drawable.ic_provider_perplexity
        "ppio" -> R.drawable.ic_provider_ppio
        "qiniu" -> R.drawable.ic_provider_qiniu
        "qwen" -> R.drawable.ic_provider_qwen
        "replicate" -> R.drawable.ic_provider_replicate
        "sambanova" -> R.drawable.ic_provider_sambanova
        "search1api" -> R.drawable.ic_provider_search1api
        "sensenova" -> R.drawable.ic_provider_sensenova
        "siliconcloud" -> R.drawable.ic_provider_siliconcloud
        "spark" -> R.drawable.ic_provider_spark
        "stepfun" -> R.drawable.ic_provider_stepfun
        "straico" -> R.drawable.ic_provider_straico
        "streamlake" -> R.drawable.ic_provider_streamlake
        "supergrok" -> R.drawable.ic_provider_supergrok
        "taichu" -> R.drawable.ic_provider_taichu
        "tencentcloud" -> R.drawable.ic_provider_tencentcloud
        "togetherai" -> R.drawable.ic_provider_togetherai
        "unsloth" -> R.drawable.ic_provider_unsloth
        "upstage" -> R.drawable.ic_provider_upstage
        "v0" -> R.drawable.ic_provider_v0
        "vercelaigateway" -> R.drawable.ic_provider_vercelaigateway
        "vertexai" -> R.drawable.ic_provider_vertexai
        "vllm" -> R.drawable.ic_provider_vllm
        "volcengine" -> R.drawable.ic_provider_volcengine
        "volcenginecodingplan" -> R.drawable.ic_provider_volcenginecodingplan
        "wenxin" -> R.drawable.ic_provider_wenxin
        "xai" -> R.drawable.ic_provider_xai
        "xiaomimimo" -> R.drawable.ic_provider_xiaomimimo
        "xinference" -> R.drawable.ic_provider_xinference
        "zai" -> R.drawable.ic_provider_zai
        "zenmux" -> R.drawable.ic_provider_zenmux
        "zeroone" -> R.drawable.ic_provider_zeroone
        "zhipu" -> R.drawable.ic_provider_zhipu
        else -> null
    }
}
